Repository prose-im/prose-app-macos, pull requests merged in 2022-06, with the labels that each got.

#54 chore: Fix previews in Xcode 14
  Prose/Prose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Prose/ProseLib/Sources/App/AppReducer.swift
  Prose/ProseLib/Sources/AuthenticationFeature/AuthenticationScreen.swift
  Prose/ProseLib/Sources/AuthenticationFeature/BasicAuthView.swift
  Prose/ProseLib/Sources/AuthenticationFeature/MFA6DigitsView.swift
  Prose/ProseLib/Sources/AuthenticationFeature/MFAView.swift
  Prose/ProseLib/Sources/ConversationFeature/ChatWithMessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/ConversationInfoView.swift
  Prose/ProseLib/Sources/MainWindowFeature/MainScreen.swift
  Prose/ProseLib/Sources/SidebarFeature/Footer/Footer.swift
  Prose/ProseLib/Sources/SidebarFeature/Footer/FooterAvatar.swift
  Prose/ProseLib/Sources/SidebarFeature/NavigationDestinationView.swift
  Prose/ProseLib/Sources/SidebarFeature/Sections/FavoritesSection.swift
  Prose/ProseLib/Sources/SidebarFeature/Sections/GroupsSection.swift
  Prose/ProseLib/Sources/SidebarFeature/Sections/OtherContactsSection.swift
  Prose/ProseLib/Sources/SidebarFeature/Sections/SpotlightSection.swift
  Prose/ProseLib/Sources/SidebarFeature/Sections/TeamMembersSection.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarContentView.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarView.swift
  Prose/ProseLib/Sources/TcaHelpers/OptionalPaths.swift
Labels: bug

#59 feat: Implement sending DM
  Prose/ProseLib/Sources/App/AppReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageView.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBarTextField.swift
  Prose/ProseLib/Sources/MainWindowFeature/MainScreen.swift
  Prose/ProseLib/Sources/ProseCoreStub/MessageStore.swift
  Prose/ProseLib/Sources/SharedModels/ChatModel.swift
Labels: feature

#67 Integrate core lib
  Makefile
  Prose/Prose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/App/AppReducer.swift
  Prose/ProseLib/Sources/AuthenticationFeature/Authentication+TemporaryFix.swift
  Prose/ProseLib/Sources/AuthenticationFeature/AuthenticationScreen.swift
  Prose/ProseLib/Sources/AuthenticationFeature/BasicAuthReducer.swift
  Prose/ProseLib/Sources/AuthenticationFeature/BasicAuthView.swift
  Prose/ProseLib/Sources/AuthenticationFeature/MFA6DigitsView.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageView.swift
  Prose/ProseLib/Sources/ConversationFeature/ChatWithMessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/Toolbar/Toolbar.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/ConversationInfoView.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/Sections/IdentitySection.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/Sections/InformationSection.swift
  Prose/ProseLib/Sources/MainWindowFeature/MainScreen.swift
  Prose/ProseLib/Sources/ProseCore/Credential.swift
  Prose/ProseLib/Sources/ProseCore/ProseClient.swift
  Prose/ProseLib/Sources/ProseCoreStub/MessageStore.swift
  Prose/ProseLib/Sources/ProseCoreStub/SecurityStore.swift
  Prose/ProseLib/Sources/ProseCoreStub/StatusStore.swift
  Prose/ProseLib/Sources/ProseCoreStub/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreStub/UserStore.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Noop.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/JID+ProseCore.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Roster.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/User.swift
  Prose/ProseLib/Sources/SharedModels/EquatableError+ProseCore.swift
  Prose/ProseLib/Sources/SharedModels/JID.swift
  Prose/ProseLib/Sources/SharedModels/None.swift
  Prose/ProseLib/Sources/SidebarFeature/Footer/Footer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarReducer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarView.swift
  Prose/ProseLib/Sources/TcaHelpers/Effect+Cancellation.swift
  Prose/ProseLib/Sources/UnreadFeature/UnreadScreen.swift
  Prose/ProseLib/Sources/UnreadFeature/UnreadSection.swift
  ProseCore/Package.swift
Labels: feature

#65 chore: Replace SwiftUI chat view by a `WKWebView`
  BuildTools/swiftgen.yml
  Makefile
  Prose/ConversationFeaturePreview/Assets.xcassets/AccentColor.colorset/Contents.json
  Prose/ConversationFeaturePreview/Assets.xcassets/AppIcon.appiconset/Contents.json
  Prose/ConversationFeaturePreview/Assets.xcassets/Contents.json
  Prose/ConversationFeaturePreview/ContentView.swift
  Prose/ConversationFeaturePreview/ConversationFeaturePreview.entitlements
  Prose/ConversationFeaturePreview/ConversationFeaturePreviewApp.swift
  Prose/ConversationFeaturePreview/Preview Content/Preview Assets.xcassets/Contents.json
  Prose/Prose.xcodeproj/project.pbxproj
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/Bundle+Fix.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/Generated/.gitkeep
  Prose/ProseLib/Sources/ConversationFeature/Generated/Files+Generated.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/.gitkeep
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/.gitkeep
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/index.93e7479b.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/index.ea5f17a4.css
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/index.html
  Prose/ProseLib/Sources/ConversationFeature/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseUI/Avatar.swift
Labels: feature

#68 chore: Refactor and improve `SettingsFeature`
  Prose/Prose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Prose/ProseLib/Package.resolved
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/App/AppScene.swift
  Prose/ProseLib/Sources/AppLocalization/Generated/Strings+Generated.swift
  Prose/ProseLib/Sources/AppLocalization/Resources/en.lproj/Localizable.strings
  Prose/ProseLib/Sources/SettingsFeature/AccountSettings/AccountSettingsAccountView.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountSettings/AccountSettingsFeaturesView.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountSettings/AccountSettingsSecurityView.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountsSettingsAccountComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountsSettingsFeaturesComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountsSettingsSecurityComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountsSettingsTabsComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/AccountsSettingsView.swift
  Prose/ProseLib/Sources/SettingsFeature/Atoms/AccountPickerRow.swift
  Prose/ProseLib/Sources/SettingsFeature/Atoms/ConnectionStatusIndicator.swift
  Prose/ProseLib/Sources/SettingsFeature/Atoms/FormGroupBoxStyle.swift
  Prose/ProseLib/Sources/SettingsFeature/Atoms/TableFooterButton.swift
  Prose/ProseLib/Sources/SettingsFeature/Atoms/VideoPreviewView.swift
  Prose/ProseLib/Sources/SettingsFeature/CallsSettingsView.swift
  Prose/ProseLib/Sources/SettingsFeature/Extensions/CommandGroup+AppSettings.swift
  Prose/ProseLib/Sources/SettingsFeature/Extensions/Preferences+Extension.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/AccountsSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/AdvancedSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/CallsSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/GeneralSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/MessagesSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/PreferencePanes/NotificationsSettingsViewController.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsConstants.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsFormFieldComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsFormFieldLabelComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsPickAccountComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsPickActionComponent.swift
  Prose/ProseLib/Sources/SettingsFeature/SettingsView.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/AccountsTab.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/AdvancedTab.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/CallsTab.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/GeneralTab.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/MessagesTab.swift
  Prose/ProseLib/Sources/SettingsFeature/Tabs/NotificationsTab.swift
Labels: enhancement
