Repository prose-im/prose-app-macos, pull requests merged in 2022-08, with the labels that each got.

#90 chore: Fix hot color scheme change
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
Labels: enhancement

#88 feat: Implement features from `prose-core-views` 0.4.0...0.9.0
  Makefile
  Prose/ConversationFeaturePreview/ContentView.swift
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/App/AppEnvironment.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageMenu.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/WKWebView+Ext.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.33ec36c2.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.35320a5c.css
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.600bf6f5.css
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.ff23c167.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.html
  Prose/ProseLib/Sources/MainWindowFeature/MainScreen.swift
  Prose/ProseLib/Sources/PasteboardClient/PasteboardClient.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Foundation+Ext.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Noop.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Chat.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseUI/View+OnKeyDown.swift
  Prose/ProseLib/Sources/Toolbox/DecodingError+Description.swift
Labels: feature

#96 feat: Custom emoji picker
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageMenu.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ReactionPickerView.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseUI/ReactionPicker.swift
  Prose/ProseUITests/RosterSelectionTests.swift
Labels: feature

#98 feat: Bump `prose-core-views` to `0.10.0`
  Makefile
  Prose/ProseLib/Sources/AppLocalization/Generated/Strings+Generated.swift
  Prose/ProseLib/Sources/Assets/Generated/Images+Generated.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.87e2e4be.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.ff23c167.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.html
  Prose/ProseLib/Sources/PreviewAssets/Generated/Assets+Generated.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Foundation+Ext.swift
  Prose/ProseLib/Sources/ProseCoreTCA/OrderedCollections+Ext.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
Labels: enhancement

#99 feat: Bump `prose-core-views` to `0.10.1`
  Makefile
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageMenu.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.5493a294.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.87e2e4be.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.html
Labels: enhancement

#100 feat: Bump `prose-core-views` to `0.10.2`
  Makefile
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/MessageMenu.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ReactionPickerView.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.07e1eb0c.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.5493a294.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.html
Labels: enhancement

#104 feat: Bump `prose-core-views` to `0.11.1`
  Makefile
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.228bcf96.css
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.61119c17.css
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.html
Labels: bug

#105 Move core views into separate target
  BuildTools/swiftgen.yml
  Makefile
  Prose/Prose.xcodeproj/xcshareddata/xcschemes/Prose.xcscheme
  Prose/Prose/AllTests.xctestplan
  Prose/Prose/UnitTests.xctestplan
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/CoreViews.swift
  Prose/ProseLib/Sources/ConversationFeature/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/JID.swift
  Prose/ProseLib/Sources/ProseCoreViews/API/MessagingContext.swift
  Prose/ProseLib/Sources/ProseCoreViews/API/MessagingStore.swift
  Prose/ProseLib/Sources/ProseCoreViews/FFI.swift
  Prose/ProseLib/Sources/ProseCoreViews/Generated/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Generated/Files+Generated.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/Bundle+Fix.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/IdentifiedArray+Difference.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/JSEventError.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/JSHelpers.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/NSError+JavaScript.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/WKUserContentController+TCA.swift
  Prose/ProseLib/Sources/ProseCoreViews/Resources/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/action-more.77dcdfab.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/action-reactions.7a469ec6.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/file-other-option-get.a1a4420f.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.1fb23577.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.228bcf96.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.html
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/origin-attribute-insecure.aa6021b6.svg
  Prose/ProseLib/Sources/ProseCoreViews/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/ColorScheme.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/EventOrigin.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/MessageAction.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/MessageEvent.swift
  Prose/ProseLib/Tests/ProseCoreViewsTests/FFITests.swift
  Prose/ProseLib/Tests/ProseCoreViewsTests/IdentifiedArrayDifferenceTests.swift
Labels: test

#102 feat: Bump `prose-core-views` to `0.11.0`
  BuildTools/swiftgen.yml
  Makefile
  Prose/Prose.xcodeproj/xcshareddata/xcschemes/Prose.xcscheme
  Prose/Prose/AllTests.xctestplan
  Prose/Prose/UnitTests.xctestplan
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/WKWebView+Ext.swift
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.07e1eb0c.js
  Prose/ProseLib/Sources/ConversationFeature/Resources/Views/messaging.35320a5c.css
  Prose/ProseLib/Sources/ConversationFeature/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/JID.swift
  Prose/ProseLib/Sources/ProseCoreViews/API/MessagingContext.swift
  Prose/ProseLib/Sources/ProseCoreViews/API/MessagingStore.swift
  Prose/ProseLib/Sources/ProseCoreViews/FFI.swift
  Prose/ProseLib/Sources/ProseCoreViews/Generated/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Generated/Files+Generated.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/Bundle+Fix.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/IdentifiedArray+Difference.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/JSEventError.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/JSHelpers.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/NSError+JavaScript.swift
  Prose/ProseLib/Sources/ProseCoreViews/Helpers/WKUserContentController+TCA.swift
  Prose/ProseLib/Sources/ProseCoreViews/Resources/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/.gitkeep
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/action-more.77dcdfab.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/action-reactions.7a469ec6.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/file-other-option-get.a1a4420f.svg
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.1fb23577.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.228bcf96.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.html
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/origin-attribute-insecure.aa6021b6.svg
  Prose/ProseLib/Sources/ProseCoreViews/Target+Logger.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/ColorScheme.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/EventOrigin.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/MessageAction.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/MessageEvent.swift
  Prose/ProseLib/Tests/ProseCoreViewsTests/FFITests.swift
  Prose/ProseLib/Tests/ProseCoreViewsTests/IdentifiedArrayDifferenceTests.swift
Labels: enhancement

#106 chore: Avoid useless mapping to `ProseCoreViews.Message`
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ProseCoreTCA/OrderedCollections+Ext.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreViews/Types/MessageEvent.swift
  Prose/ProseLib/Sources/TestHelpers/Date+YMD.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/MessageReactionsTests.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/ProseClientTests.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/TypesEncodingTests.swift
Labels: enhancement, performance

#108 feat: Improve typing indicator
  Prose/ProseLib/Sources/AppLocalization/Generated/Strings+Generated.swift
  Prose/ProseLib/Sources/AppLocalization/Resources/en.lproj/Localizable.strings
  Prose/ProseLib/Sources/AppLocalization/Resources/en.lproj/Localizable.stringsdict
  Prose/ProseLib/Sources/ConversationFeature/Chat/TypingIndicator.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/TypingIndicator.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/JID.swift
Labels: enhancement

#109 Load one page of messages from archive
  Prose/Prose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Noop.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient.swift
Labels: feature

#110 feat: Dynamically show typing indicator
  Prose/ConversationFeaturePreview/ContentView.swift
  Prose/Prose.xcodeproj/xcshareddata/xcschemes/ConversationFeaturePreview.xcscheme
  Prose/Prose/AllTests.xctestplan
  Prose/Prose/UnitTests.xctestplan
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBarTextField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/TypingIndicator.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/JID.swift
  Prose/ProseLib/Tests/ConversationFeatureTests/TypingIndicatorTests.swift
Labels: feature

#113 feat: Allow message edition
  Prose/ConversationFeaturePreview/ContentView.swift
  Prose/ProseLib/Sources/AppLocalization/Generated/Strings+Generated.swift
  Prose/ProseLib/Sources/AppLocalization/Resources/en.lproj/Localizable.strings
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/EditMessageView.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageAttachmentsButton.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBarTextField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageComposingField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageEmojisButton.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageFormattingButton.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/TypingIndicator.swift
  Prose/ProseLib/Sources/ProseCore/ProseClient.swift
  Prose/ProseLib/Sources/ProseCore/ProseClientProtocol.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Chat.swift
  Prose/ProseLib/Sources/TcaHelpers/Reducer+Changes.swift
  Prose/ProseLib/Tests/ConversationFeatureTests/TypingIndicatorTests.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/Helpers/ProseMockClient.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/ProseClientTests.swift
Labels: feature

#118 feat: Mark edited messages as such
  Makefile
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.1fb23577.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.228bcf96.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.ade4f812.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.bf558111.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.html
  Prose/ProseLib/Tests/ProseCoreTCATests/TypesEncodingTests.swift
Labels: enhancement

#76 feat: Add popups to start new conversations
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/AppLocalization/Generated/Strings+Generated.swift
  Prose/ProseLib/Sources/AppLocalization/Resources/en.lproj/Localizable.strings
  Prose/ProseLib/Sources/JoinChatFeature/AddMemberSheet.swift
  Prose/ProseLib/Sources/JoinChatFeature/JoinGroupSheet.swift
  Prose/ProseLib/Sources/SidebarFeature/RosterReducer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarReducer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarView.swift
Labels: feature

#120 feat: Show avatar images
  Makefile
  Prose/ConversationFeaturePreview/ContentView.swift
  Prose/EditProfileFeaturePreview/EditProfileFeaturePreviewApp.swift
  Prose/Prose.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Prose/ProseLib/Package.swift
  Prose/ProseLib/Sources/App/AppEnvironment.swift
  Prose/ProseLib/Sources/App/AppReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/Chat.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatReducer.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/ChatSessionState.swift
  Prose/ProseLib/Sources/ConversationFeature/Chat/EditMessageView.swift
  Prose/ProseLib/Sources/ConversationFeature/ConversationScreen.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageBar.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageComposingField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/MessageField.swift
  Prose/ProseLib/Sources/ConversationFeature/MessageBar/TypingIndicator.swift
  Prose/ProseLib/Sources/ConversationFeature/Toolbar/Toolbar.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/ConversationInfoView.swift
  Prose/ProseLib/Sources/ConversationInfoFeature/Sections/SecuritySection.swift
  Prose/ProseLib/Sources/EditProfileFeature/EditProfileScreen.swift
  Prose/ProseLib/Sources/EditProfileFeature/Sidebar/Sidebar.swift
  Prose/ProseLib/Sources/EditProfileFeature/Sidebar/SidebarHeader.swift
  Prose/ProseLib/Sources/MainWindowFeature/MainScreen.swift
  Prose/ProseLib/Sources/NotificationsClient/NotificationsClient+Live.swift
  Prose/ProseLib/Sources/NotificationsClient/NotificationsClient+Noop.swift
  Prose/ProseLib/Sources/NotificationsClient/NotificationsClient.swift
  Prose/ProseLib/Sources/ProseCore/ProseClient.swift
  Prose/ProseLib/Sources/ProseCore/ProseClientProtocol.swift
  Prose/ProseLib/Sources/ProseCoreTCA/AvatarImageCache.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Live.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient+Noop.swift
  Prose/ProseLib/Sources/ProseCoreTCA/ProseClient.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/Message.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/SessionState.swift
  Prose/ProseLib/Sources/ProseCoreTCA/Types/UserInfo.swift
  Prose/ProseLib/Sources/ProseCoreViews/API/MessagingStore.swift
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.31e18c80.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.92586743.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.ade4f812.js
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.bf558111.css
  Prose/ProseLib/Sources/ProseCoreViews/Resources/Views/messaging.html
  Prose/ProseLib/Sources/SidebarFeature/Footer/Footer.swift
  Prose/ProseLib/Sources/SidebarFeature/Footer/FooterAvatar.swift
  Prose/ProseLib/Sources/SidebarFeature/RosterReducer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarReducer.swift
  Prose/ProseLib/Sources/SidebarFeature/SidebarView.swift
  Prose/ProseLib/Sources/TestHostApp/Mocks/AppState.swift
  Prose/ProseLib/Sources/Toolbox/CGImage+Prose.swift
  Prose/ProseLib/Sources/Toolbox/ItemProvider+Prose.swift
  Prose/ProseLib/Sources/Toolbox/PlatformImage.swift
  Prose/ProseLib/Tests/ConversationFeatureTests/TypingIndicatorTests.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/Helpers/ProseMockClient.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/ProseClientTests.swift
  Prose/ProseLib/Tests/ProseCoreTCATests/TypesEncodingTests.swift
Labels: feature
